### ISSUE TITLE
Die Erstellung von Seriennummern für Waffen erzeugt bei Items anderer Art auch Seriennummern

### ISSUE THREAD

**Issue by 1stNox** [vImpact/vi-roleplay-roadmap#108]
![Image](https://user-images.githubusercontent.com/44528748/200136520-ea8a0912-63e5-4df3-8138-db6cb5e3c87e.png)

**Comment by C-PT** [comment]
Ist gefixt. Siehe: https://github.com/vImpact/vi-roleplay/pull/59
