### ISSUE TITLE
Report Button

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#18]
Alles in einem Bereich der Streaming-Reichweite wird protokolliert
- User welcher den Report erstellt hat
- Spieler und deren Status (Position, Essen, Trinken, Energie, Skill-Level, Leben, Weste, Waffen (unterteilt in Inventar und Ausgerüstet so wie in der Hand habend), Munition der Waffen, und allgemein alle Gegenstände im Inventar)
- Fahrzeuge und deren Status (Position, Gegenstände im Kofferraum, Treibstoffstand, Schadensstatus)
- Schadensdatenbank (wer hat wem wann wie viel Schaden zugefügt und womit - letzte 5 Minuten)

Dem Bericht wird eine Nummer zugewiesen, die im Support benannt werden kann, damit der Support auf diese Protokolle zugreifen kann (Nummer generiert aus Datum, Uhrzeit und Aufzählung -> 2910202204120001 -> 29.10.2020 22:04:12 0001 Nummern

Der Ersteller des Berichts sollte in den Bericht aufgenommen werden. Außerdem wird die Report-ID im UCP bei dem Nutzer gespeichert werden, damit der Benutzer sie wiederfinden kann (manche sind dumm).

Diese Nummer wird dem Spieler IC angezeigt, das entsprechende Frontend folgt dazu.
- Die Supportmeldung wird für 12 Sekunden angezeigt.
- Wenn man während der Supportmeldung erneut F7 drückt (während der 12 Sekunden), wird in der oberen rechten Ecke unter der Supportmeldung ein Textfeld eingefügt, in das man weitere Informationen eingeben kann.
- Die Supportmeldung/ID wird dann auch angezeigt (auch wenn der Timer von 12 Sekunden bereits abgelaufen ist), bis man den Text abgeschickt hat.

Tickets haben einen Cooldown von 30 Sekunden.

Erstellt innerhalb der 12 Sekunden ein Nutzer, welcher sich in der halben Streaming Range befindet ebenfalls ein Ticket, muss nicht erneut alles erfasst werden, sondern das Ticket wird mit einer neuen Aufzählung einfach dupliziert und auf den 2. Nutzer überschrieben.

**Comment by C-PT** [comment]
Bis auf das Frontend (derzeit nur Befehl /report [text]) und den letzten Paragraphen ("Erstellt innerhalb der 12 Sekunden ein Nutzer, welcher sich in der halben Streaming Range befindet [...]") ist alles so eingebaut. Es müsste später dann noch die Report-Nr. im UCP gespeichert werden. 

Die Report-Nr. wird auch wie angegeben generiert. Beispiel:
08102022191721**79** --> 08.10.2022 19:17:21 Uhr + 79 (79 = ID welche immer um 1 erhöht wird, sobald ein Report erstellt wird) Dementsprechend werden die Nummer recht lang. Darüber habe ich auch schon mit Herrn Doktor Tod gesprochen. Alternativ könnte man nur die ID (in dem Fall 79) für den Spieler angeben. Dann kann aber natürlich auch jeder Spieler nachvollziehen wie viele Reports existieren usw. Das sollte man vielleicht überdenken. Eventuell einfach eine Zufallsgenerierte Zahl die kürzer ist?

**Comment by 1stNox** [comment]
@C-PT Ich habe mir mal die Anforderungen durchgelesen.
Daraus resultieren folgende Änderungen.

- [ ] request_number entfernen
- [ ] id ändern, kein Index verwenden, sondern ID serverseitig mit dem GuidGenerator erstellen.
- [ ] JSON Formation aus character_blob entfernen (Absatz Zeichen und Leerzeichen nach Kommata bspw.)

**Comment by C-PT** [comment]
@1stNox Erledigt. Siehe Pull Request: https://github.com/vImpact/vi-roleplay/pull/48
