### ISSUE TITLE
Waffensystem

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#21]
### Beschreibe deinen Wunsch

https://docs.google.com/document/d/1G66Oj9JqX1OdzeR82q03TOMpmt3M5jpn4JtdjyKLehY/edit

### Zusätzlicher Kontext

https://juri.gq/images/2022-Mai-01-1798.png

Animationen **`zu Release`**

der Rest **`nach Release`**

**Comment by Phate777** [comment]
Player PEDs:
mp_f_freemode_01 (0x9C9EFFD8)
mp_m_freemode_01 (0x705E61F2)
