### ISSUE TITLE
Housing System

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#26]
Wenn man ein Haus kauft (nur beim Kauf, nicht bei der Miete), hat man die Möglichkeit, das Haus wie in GTA 5 Online anzupassen (unterschiedliches Aussehen von Wänden, Böden, Decken, eventuell Addons wie ein Safe, wenn es einen gibt usw.)

Man bekommt das Innere der Wohnung angezeigt und über das Frontend dann die verschiedenen Optionen, es zu bearbeiten. Wie das IPL es dann hergibt (es gibt mehrere Wohnungen).

Änderungen (also wenn man es nicht als Standard kaufen will) kosten dann auch extra Geld, das dann zusammen mit dem Wohnungspreis abgebucht wird.

Dies kann man auch noch nach dem Kauf ändern und anpassen.

**Comment by YuriRodriguez** [comment]
**`nach Release`**
