### ISSUE TITLE
Fahrzeug Shop

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#31]
Man geht an einen beliebigen Fahrzeugshop, drückt "E" an einem Auto und es öffnet sich die Detailansicht des Autos.

Man geht zum NPC des Ladens und man bekommt die Kaufansicht und kann das Fahrzeug entsprechend auswählen und kaufen.

**Comment by Renegade1912** [comment]
UI implementiert, folgene Punkte sind noch im Frontend/Backend zu erledigen:

- [ ] Backend des Fahrzeugsshops neustrukturieren um den Kauf-/Previewprozess abzubilden
- [ ] Die im Frontend benöigten Daten (siehe CarDealership.ts - CarDealerCreate) vom Backend aus bereitstellen
- [ ] Beim Öffnen lokal das erste Fahrzeug spawnen
- [ ] Beim Wechseln des Fahrzeuges das entsprechende Fahrzeug de-/spawnen
- [ ] Beim Farbwechsel die Fahrzeugfarbe anpassen
- [ ] Kaufevent im Backend implementieren
