### ISSUE TITLE
Ersetzen | Shopsystem

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#34]
- [ ] type muss von dem Server vorgegeben werden können
- [ ] Titel, Beschreibung und Bild sind vom Type abhängig automatisch eingefügt
- [ ] canRob muss von dem Server vorgegeben werden können
- [ ] maxWeight muss von dem Server vorgegeben werden können
- [ ] products muss von dem Server vorgegeben werden können
- [ ] requsities muss von dem Server vorgegeben werden können, alternativ ist der Standwert immer Bargeld
- [ ] Kategorien müssen so angepasst werden, dass jede Shop Variante den Reiter alles beinhaltet; die restlichen Reiter werden dynamisch erzeugt
- [ ] Die Produktzuordnung muss so angepasst werden, dass jedes Item sowohl zu Alles, als auch zur richtigen Kategorie gehört

**Comment by Renegade1912** [comment]
- Kategorie "Alles" zu Kategorien "adden"

**Comment by Renegade1912** [comment]
Fehlende Bilder:

- Logo Robs
- Logo Pharmacia
