### ISSUE TITLE
Ersetzen | Char Selector

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#35]
Frontend vorhanden

**Comment by SokratesMir** [comment]
- [ ]  is_deactivated = char gesperrt
- [ ] in der datenbank fehlt entsprechender bann grund
- [ ] letzter login (bitte von farbe rot in farbe blau #1363DF oder ähnliches)
- [ ] letzter login muss aus der db abgegriffen werden und rüber geschickt werden
- [ ] ankfunft muss aus der db abgegriffen werden und rüber geschickt werden
