### ISSUE TITLE
Ersetzen | Garagensystem

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#36]
Frontend vorhanden

**Comment by Renegade1912** [comment]
**Benötigte Events Backend:**

- Garage:SetCarFavourite

**Comment by 1stNox** [comment]
Ja, mache ich eben @Renegade1912

**Comment by 1stNox** [comment]
Sollte erledigt sein, müsstest du sonst einmal testen, dazu kam ich leider noch nicht.
Habe die DDL der Vehicle Tabelle auch mit hochgeladen, musst eine neue Spalte anlegen.
Name ist favourite, type ist boolean, Standardwert ist false, und die Spalte kann nicht null sein.
Sende dir jetzt auch den Favourite Status beim Öffnen der Garage mit.

Fehlt da sonst etwas @Renegade1912

**Comment by Renegade1912** [comment]
Danke @1stNox 

Grundsätzlich sollte erstmal nichts weiteres fehlen.
