### ISSUE TITLE
Farmsystem

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#40]
### Beschreibung des Problems

Man sollte mit E sachen an den Spots verarbeiten können,
es gibt keine Areas, keine NPC´s, man kann weder Sammeln noch Verarbeiten.

### Reproduzierung

Man geht an einen Farmspot und Drückt "E", dort passiert nix

### Eigentliches Verhalten

Die Funkion sollte vorhanden sein, damit man verarbeiten kann.

**Comment by C-PT** [comment]
Sollte nun durch die neuen polygon ColShapes behoben sein.
