### ISSUE TITLE
Minijobs Auto Aussteigen

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#41]
### Beschreibung des Problems

Aktuell muss man im Minijob Fahrzeug sitzenbleiben damit der Progressbar läuft.

### Reproduzierung

Man startet einen Minijob, fährt zum Punkt steigt aus und es kommt eine Fehlermeldung nach einer Zeit, dass das Fahrzeug nicht meh rin der nähe ist.

### Eigentliches Verhalten

Man muss aus dem Fahrzeug Aussteigen zum Punkt Laufen und E Drücken dabei spielt sich eine Animation ab.

**Comment by C-PT** [comment]
Sollte behoben sein.
