### ISSUE TITLE
Fraktionssystem - Jede Fraktion

### ISSUE THREAD

**Issue by Lirrox** [vImpact/vi-roleplay-roadmap#44]
### Beschreibe deinen Wunsch

- [ ] Rechnungen
      - Über Kreismenü kann Fraktionsmitglied Rechnungen ausstellen, wenn er sein gegenüber anschaut
      - Erst bekommt das Fraktionsmitglied die Ansicht, in der er Grund der Rechnung und Preis eingeben kann, was er dann bestätigen muss
      - Dann bekommt es der Gegenüber, welcher dann Bestätigen oder Ablehnen kann.
      - Bei Bestätigung kann er auswählen ob Bar oder mit Karte
      - außerdem bekommt er bei bezahlung eine Quittung in sein Inventar als Item die er Benutzen (öffnen), weitergeben oder wegwerfen kann (Sieht dann aus wie ein DinA4 Blatt)
      - Bar wird Geld aus Inventar genommen und bei Karte wird das vom Konto abgebucht und auf das Fraktionskonto gebucht.

- [ ] Spind
      - Privater Lagerplatz für Items > Funktioniert wie Kofferaum Inventar (öffnet sich also im Inventar nebenan)
      - an einem Punkt (gesetzte Koordinate) kann via Interaktion "E" ein Dropdown Menü geöffnet werden, inder man die Spindnummern sieht und darin seinen Spind suchen kann, für den man einen Schlüssel hat > per "Enter" kann man es bestätigen und es öffnet sich im Inventar
      - Schlüssel muss individuell sein > also selbe Nummer haben wie Spind (der einfachheit halber sollte man eine beliebig erweiterbare Item anzahl an schlüsseln schon eingefügt haben, sodass nichts durch das system erzeugt werden muss)
      - Mit Universalschlüssel kann jeder Spind der Fraktion geöffnet werden

- [ ] Türen
      - Die Türen in Fraktionsgebäude sind alle ab(auf-)schließbar, welche durch Schlüsselkarten (item) geöffnet werden können - Per E Interaktion
      - Schlüsselkarten sollen im Fraktionsverwaltungssystem "programmierbar" sein, d.h. ich kann die TürIDs auf die Schlüsselkarten packen und sagen, welche Türe die Karte öffnen kann

- [ ] Fraktionsgaragen
      - funktionieren wie normale Garagen und haben selbes UI
      - nur Fraktionsautos können darin geparkt werden
      - jede Fraktion hat eigene Garagen und kann nur auf ihre Garagen zugreifen

- [ ] Computer
      - Siehe Fraktionsverwaltungssystem (noch nicht angelegt)

- [ ] Leitstellen Telefone
      - im HQ kann ich an einem gesetzten Ort (koordinate) via E-Interaktion mein Handy mit der Leitstelle koppeln //Oder entkoppeln
      - wenn jemand dann die jeweilige Notrufnummer der Fraktion anruft, klingelt es bei dem gekoppelten Spieler
      - gekoppelter Spieler sieht den Notruf auf dem Handy anders als normale Anrufe (anderer Hintergrund, anderer Klingelton) damit es sich abhebt

- [ ] Ein-/Ausstempeln
      - an einem Spot können sich Spieler (über E) In den Dienst (ab-)melden, sodass man Geld verdient **(muss über Servershutdown oder restarts hinweg bestehen bleiben!)**
      - der Spot ist Fraktionsspezifisch und in deren HQ
      - angemeldete Leute müssen im Fraksystem (am PC) gelistet sein und geloggt werden

- [ ] Schriftstücke
      - Siehe Schriftstück Git Beitrag (noch nicht da)

### Zusätzlicher Kontext

Fraktionskonzept Allgemein
https://docs.google.com/document/d/1PMC0ovaTYKOZLpNwuk7_EcaNSpRcSW06UhrszQBXgZA/edit

Fraktionssystem - Verwaltungssystem - Webeinbindung
https://docs.google.com/document/d/1UTSM8LXaDzZJnV_c4kUkG-KVSd0e4PDm2i0peoELsWU/edit#heading=h.b683ephp5cby

**Comment by YuriRodriguez** [comment]
Computer und Schriftstücke (bzw die ui funktionen dahinter) **`nach Release`**
evtl dazu externe systeme per Webview einbinden (z.B. Cop net Emergency OS oder ähnliche)
