### ISSUE TITLE
ATM umgehen der PIN eingabe

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#47]
### Beschreibung des Problems

wenn man bei einem beliebigen ATM sich Anmeldet kann man mit dem Linken unteren äußeren Button (siehe Bild und Video) die Eingeblendete PIN eingabe Umgehen und hat somit zugriff auf das Konto
https://juri.gq/images/2022-Juni-05-1890.png

### Reproduzierung

man geht an einem ATM und betätigt den Knopf im Video
http://juri.gq/files/2022-Juni-05-1892.mp4
http://juri.gq/files/2022-Juni-05-1893.mp4

### Eigentliches Verhalten

es sollte wie bei den anderen Buttons nix passieren solange man nicht die richtige PIN eingibt

### Zusätzlicher Kontext

http://juri.gq/files/2022-Juni-05-1892.mp4
https://juri.gq/images/2022-Juni-05-1890.png
http://juri.gq/files/2022-Juni-05-1893.mp4

**Comment by mats-voss** [comment]
### Zusätzliche Probleme

1. Unbegrenzte Eingabe von PIN-Ziffern → Sternchen gehen über Eingabefeld hinaus.
2. Bei Fehlermeldung werden die Sternchen der vorherigen Eingabe "in/hinter" dem Tastenfeld angezeigt.
3. Wenn man die UI nach einer falschen Eingabe schließt, wird die UI bei weitern falschen versuchen nur geschlossen und die Karte wird nie gesperrt.
4. Nach 3 falschen eingaben wird die UI soft geschlossen ohne dass man eine Nachricht angezeigt bekommt das die Karte gesperrt wurde.

### Reproduzierung

1. Ganz viele Ziffern eingeben.
2. Einen falschen PIN eingeben und bestätigen.
3. Einen falschen PIN eingeben und bestätigen, die UI wieder öffnen und erneut einen falschen PIN eingeben → mehrfach wiederhohlen.
4. Dreimal eine Falsche PIN eingeben.

### Zusätzlicher Kontext
3. → Eingabe auf 4 Ziffern beschränkt.
