### ISSUE TITLE
Tankarten Tankstellen im Backend

### ISSUE THREAD

**Issue by DeadShot-cx** [vImpact/vi-roleplay-roadmap#73]
Diesel nach ganz unten. Auflistung wie folgt:

Strom
Regular
Mid Grade
Premium
Diesel

Nicht jede Tankstelle hat Strom. pauschal einfach nur bei 50% der Tankstellen.

Spezielle Tankstandorte für Boote, Flugzeuge etc. (Kerosin - nichts anderes).

**Comment by Renegade1912** [comment]
- [ ] Reihenfolge
