### ISSUE TITLE
ATM - Pin eingabe mittels Tastatur (Numpad und oder Zahlenreihe)

### ISSUE THREAD

**Issue by YuriRodriguez** [vImpact/vi-roleplay-roadmap#80]
### Beschreibe deinen Wunsch

Am ATM die Pineingabe über das Numpad oder die Normale Zahlenreihe auf der Tastatur ermöglichen,
um den Schutz vor Meta bei Streamern zu verbessern.
(wenn man die Zahlen per Maus eintippt sieht ein findiger Zuschauer (mit iq von über 20) welche Pin man eingegeben hat)

### Zusätzlicher Kontext

[Design Vorschlag](https://juri.gq/images/2022-Oktober-19-2345.png)

**Comment by Renegade1912** [comment]
Zurückgestellt für neue UI
